---
title: "drzewo_filo"
output: html_document
---
```{r}
library(ape)
library(phangorn)
library(ggtree)
library(ggplot2)
library(apex)
library(msa)
library(stringr)
```



```{bash}
#DOpasowanie dekwencji przy pomocy muscle
source /home/janek/miniconda3/bin/activate 
conda activate muscle

muscle -align projekt_drzewo.fasta -output projekt_drzewo.afa

conda deactivate
```

```{r}
#Read Fasta file
dna_raw <- readDNAStringSet("projekt_drzewo.fasta")

#Make MMA usng muscle
aln <- msa(dna_raw, method = "Muscle")

#Save as phydat
phydat <- as.phyDat(aln, type = "DNA")

# Extract identifier (first token)
identifier <- str_extract(sequence_names, "^[^ ]+")

# Extract organism (inside brackets)
organism <- str_extract(sequence_names, "(?<=\\[).*?(?=\\])")

# Replace spaces with underscores in organism
organism <- str_replace_all(organism, " ", "_")

# Combine into new names
new_names <- paste(identifier, organism, sep = "_")


names(phydat)<-new_names
names(phydat)
```





```{r}
dist_matrix <- dist.ml(phydat)
nj_tree <- NJ(dist_matrix)


fit <- pml(nj_tree, data = phydat)

fit_opt <- optim.pml(
  fit,
  model = "GTR",  
  optInv = TRUE,
  optGamma = TRUE,
  rearrangement = "stochastic"
)

```

```{r}
set.seed(123)

bs <- bootstrap.pml(
  fit_opt,
  bs = 100   # use 500–1000 for final analysis
)

```

```{r}
tree_bs <- plotBS(
  fit_opt$tree,
  bs,
  p = 50,     # show values ≥50
  type = "none"
)

```


```{r}
p <- ggtree(tree_bs, branch.length = "none") +
  geom_tiplab(size = 3, offset = 0.5) +
  geom_hilight(node=17, fill="gold") + 
  geom_hilight(node=21, fill="purple")+
  geom_text2(aes(label = label), size = 3, hjust = -0.1) +
  scale_x_continuous(limits=c(0,40))+

  theme_tree2()

p

```
```{r}
library(ggtree)

p <- ggtree(tree_bs, branch.length = "none") +
  geom_hilight(node = 17, fill = "gold", alpha = 0.3) +
  geom_hilight(node = 21, fill = "purple", alpha = 0.3) +
  geom_tiplab(size = 3, offset = 0.5) +
  geom_text2(aes(label = label), size = 3, hjust = -0.1) +
  xlim_tree(40) +
  theme_tree2()

p

```


```{r}
# Check number of sites and sequences
phydat
```


```{r}
ggsave("phylogenetic_tree_bootstrap.png", p, width = 8, height = 8)
```




