---
title: "drzewo_filo"
output: html_document
---
```{r}
library(ape)
library(phangorn)
library(ggtree)
library(ggplot2)
library(apex)
library(msa)
library(stringr) 
library(tidyverse)
```





```{r}
#Wzytanie pliku fasta
dna_raw <- readDNAStringSet("projekt_drzewo.fasta")

#MMa przy pomocy MUSCLE
aln <- msa(dna_raw, method = "Muscle")

#Zapis jako phydat
phydat <- as.phyDat(aln, type = "DNA")

# Lista Idnryfikator
identifier <- str_extract(sequence_names, "^[^ ]+")

# lista gatunków
organism <- str_extract(sequence_names, "(?<=\\[Staphylococcus).*?(?=\\])")

#nowe identyfikaotry
new_names <- paste(identifier, organism, sep = " Staph.")

names(phydat)<-new_names
names(phydat)
```



```{r}
#Liczneie macierzy odległośći
dist_matrix <- dist.ml(phydat)

#Drzewo metodą NJ
nj_tree <- NJ(dist_matrix)

#utworzenie obiektu pml
fit <- pml(nj_tree, data = phydat)

```

```{r}
#Opytmalizacja drzewa przy użyciu GTR
fit_opt <- optim.pml(
  fit,
  optInv = TRUE,
  optGamma = TRUE,
  model = "GTR",  
  rearrangement = "stochastic"
)
```

# BootStrap
```{r}
set.seed(123)
#Liczeni bootstrap dla 1000
bs <- bootstrap.pml(
  fit_opt,
  bs = 1000
)

```

```{r}
tree_bs <- plotBS(
  fit_opt$tree,
  bs,
  p = 50,     # show values ≥50
  type = "none"
)

```


```{r}
my_tab <- as_tibble(tree_bs)
x <- my_tab %>%   mutate(TIP_COL = grepl("aureus", label, ignore.case = TRUE))
x
```

```{r}
my_tab <- as_tibble(tree_bs)
x <- my_tab %>%   mutate(TIP_COL = grepl("aureus", label, ignore.case = TRUE))
x

#Rysowanie drzewa
p <- ggtree(tree_bs, branch.length = "none") %<+% x +
  geom_tiplab(size = 3, offset = 0.5) +
  geom_nodelab(size=3, hjust = -0.1)+ #wartosći bootstrap
  geom_tippoint(aes(color = TIP_COL), size = 3) +
  scale_color_manual(
    values = c( `TRUE` = "green")
  ) +
  scale_x_continuous(limits = c(0, 18)) + #skala limity
  theme_tree2()+  #skala na dole
  theme(legend.position = "none") 

p
ggsave("phylogenetic_tree_bootstrap.png", p, width = 8, height = 8)
```



```{r}

```


```{r}
library(DiagrammeR)
```


```{r}
grViz("
digraph workflow {
  
  # Ustawienia grafu
  graph [layout = dot,
         rankdir = TB,
         fontsize = 10]
         
         

  # Domyślne style węzłów (można nadpisać indywidualnie)
  node [fontname=Helvetica, style=filled, fillcolor=LightGray]
  

  # Pliki (folder)
  DB [label='DB', shape=folder, fillcolor=Beige]
  UNIPROT [label='UNPROT', shape=folder, fillcolor=Beige]
  FASTA1 [label='plik FASTA', shape=folder, fillcolor=Beige]
  FASTA2 [label='plik FASTA', shape=folder, fillcolor=Beige]
  

  # Procesy (box)
  BLAST [label='BLAST', shape=box, fillcolor=LightBlue]
  MEGA [label='MEGA', shape=box, fillcolor=LightBlue]
  AF2 [label='AF2', shape=box, fillcolor=LightBlue]
  chimera [label='Chimera', shape=box, fillcolor=LightBlue]
  
  # Krawędzie (workflow)
  DB -> FASTA1
  DB -> BLAST
  UNIPROT -> FASTA1
  FASTA1 -> BLAST
  BLAST -> FASTA2
  FASTA2 -> AF2
  FASTA2 -> chimera
}
")
```




